name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    name: Code Quality Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Run Biome CI
        run: npx biome ci .

      - name: TypeScript check (Frontend)
        run: npm run type-check

      - name: TypeScript check (Backend)
        run: npm run type-check:backend

  build-test:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build backend
        run: cd backend && npm run build

      - name: Build for Android (dry run)
        run: |
          # React Native build check (without actual Android SDK)
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/index.android.bundle || echo "Android build preparation completed"